name: Update chains and flex index files
on:
  push:
    branches:
      - main
  schedule:
    # Run every day at 12:00
    - cron: '0 12 * * *'

jobs:
  conditional_PR_generation:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.x

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - run: pnpm install

      - name: Refresh chains and flex index files
        # If changes are present after build, set env variable
        run: |
          pnpm axios:build
          pnpm docs:build
          pnpm flex:build
          pnpm flex:test
          git diff --quiet --exit-code || echo "CHANGES_FOUND=true" >> $GITHUB_ENV

      - name: Create PR if files have changed
        if: env.CHANGES_FOUND == 'true'
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git fetch origin main
          git checkout -B ${{ env.BRANCH_NAME }} origin/main
          git commit -am "Update chains and flex index files"
          git push -f origin ${{ env.BRANCH_NAME }}
          gh pr create -B main -H ${{ env.BRANCH_NAME }} --title 'Update chains and flex index files' --body 'Created by GitHub Actions Cron Job' --reviewer wkande,dcroote
        env:
          BRANCH_NAME: "actions-chains-index-update"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
